version: '3'
services:
  goodenergy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    expose:
      - '8080'
  sqlite3:
    image: nouchka/sqlite3:latest

    